services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_db_fchat
    ports:
      - $DB_HOST_PORT:$DB_CONTAINER_PORT
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - fchatpgdata:/var/lib/postgresql/data
    networks:
      - fchat-api-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$DB_USERNAME"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: frymarshall/fchat_api
    container_name: fchat-api
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .env.prod:/app/.env
      - ./firebase-sdk.json:/app/firebase-sdk.json
    ports:
      - $PORT:$PORT
    environment:
      - NODE_ENV=prod
    networks:
      - fchat-api-network
    command: ["npm", "run", "start:prod"]

  cron:
    build:
      context: .
      dockerfile: ./backup-scripts/backup.Dockerfile
    container_name: cron_task
    restart: unless-stopped
    env_file: ./.env.prod
    volumes:
      - fchatpgcron:/backups
      - ./backup-scripts:/backup-scripts
    networks:
      - fchat-api-network

networks:
  fchat-api-network:
    driver: bridge

volumes:
  fchatpgdata:
  fchatpgcron: