services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_db_fchat
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - api-fchat_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$DB_USERNAME"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      target: $NODE_ENV
    container_name: fchat_api_2
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - .env.${NODE_ENV}:/app/.env
      - /app/node_modules
    ports:
      - $LOCAL_PORT:$DOCKER_PORT
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - api-fchat_network
    command: ["npm", "run", "start:dev"]

networks:
  api-fchat_network:
    driver: bridge