services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_db_fchat
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - api-fchat_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$DB_USERNAME"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: frymarshall/fchat_api
    container_name: fchat_api
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .env.prod:/app/.env
      - ./firebase-sdk.json:/app/firebase-sdk.json
    ports:
      - $LOCAL_PORT:$DOCKER_PORT
    environment:
      - NODE_ENV=prod
    networks:
      - api-fchat_network
      - nginx_network
    command: ["npm", "run", "start:prod"]

networks:
  nginx_network:
    external: true
  api-fchat_network:
    driver: bridge