version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE_NAME
      - MYSQLDB_USER=$MYSQL_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - fchat_network
  
  fchatapi:
    depends_on:
      - mysqldb
    container_name: fchatapi
    image: frymarshall/fchat_api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - fchat_network

volumes: 
  db:
networks:
  fchat_network:
    driver: bridge