version: '3.8'

services:

  fchatauth:
    image: frymarshall/fchat_auth
    container_name: fchatauth
    volumes:
      - ./src:/app
    ports: 
      - "4200:80"
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true