FROM node:18-alpine as builder

RUN apk add --no-cache git

WORKDIR /app

COPY . .

RUN git submodule update --init --recursive

RUN npm install

RUN npm run build

FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/auth-fchat/. /usr/share/nginx/html/
