FROM node:alpine as builder
WORKDIR /app

COPY . .
RUN git submodule update --init --recursive
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/webapp-fchat/. /usr/share/nginx/html/