version: '3.8'

services:

  fchatwebapp:
    image: frymarshall/fchat_webapp
    container_name: fchatwebapp
    volumes:
      - ./src:/app
    ports: 
      - 4201:80
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true