version: '3.8'

services:

  fchat:
    image: frymarshall/fchat_showcase
    container_name: fchat
    volumes:
      - ./src:/app
    ports: 
      - "4202:80"
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true