version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - fchat_network
  
  fchatapi:
    depends_on:
      - mysqldb
    container_name: fchatapi
    command: ["/bin/sh", "./wait-for-db.sh"]
    build: .
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - fchat_network

volumes: 
  db:
networks:
  fchat_network:
    driver: bridge