// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHGslE8pAMXQIKwgNPi8oihF0pLPTbKgU',
    appId: '1:743625608116:web:86ae7f036560a5c0cbc0e1',
    messagingSenderId: '743625608116',
    projectId: 'fchat-notifications',
    authDomain: 'fchat-notifications.firebaseapp.com',
    storageBucket: 'fchat-notifications.firebasestorage.app',
    measurementId: 'G-0XVKQH4D7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYUwZhkOAMZngbAOaXnLlyYDdUgWjmM2s',
    appId: '1:633819607940:android:33e7ca5c16c96fc9ae63d1',
    messagingSenderId: '633819607940',
    projectId: 'fchat-project',
    storageBucket: 'fchat-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApylXCTkO3EmBpfPvVTHa6y_w0RZuGHi0',
    appId: '1:633819607940:ios:a0fadeb794e62410ae63d1',
    messagingSenderId: '633819607940',
    projectId: 'fchat-project',
    storageBucket: 'fchat-project.firebasestorage.app',
    iosBundleId: 'com.example.mobileFchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKTfIEvr-GnmgdUULMBZ5kDDKPDB6azfI',
    appId: '1:743625608116:ios:e7bb6464cbda1a54cbc0e1',
    messagingSenderId: '743625608116',
    projectId: 'fchat-notifications',
    storageBucket: 'fchat-notifications.firebasestorage.app',
    iosBundleId: 'com.example.mobileFchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHGslE8pAMXQIKwgNPi8oihF0pLPTbKgU',
    appId: '1:743625608116:web:ecf9a3a240f2373acbc0e1',
    messagingSenderId: '743625608116',
    projectId: 'fchat-notifications',
    authDomain: 'fchat-notifications.firebaseapp.com',
    storageBucket: 'fchat-notifications.firebasestorage.app',
    measurementId: 'G-CPJ51090KW',
  );
}