name: Push Template

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      folder:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy ${{ inputs.component }}
        run: |
          echo "🔧 Deploying component: ${{ inputs.component }}"
          cd ${{ inputs.folder }}
          make deploy
